#spring.application.name=ControllersSec02
#spring.mustache.suffix=.html
spring:
  application:
    name: Taller3
  mustache:
    suffix: .html
  datasource:
    url: jdbc:postgresql://localhost:5500/taller3
    username: postgres
    password: P0k3M0n-212@#$
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
  sql:
    init:
      mode: never
security:
  jwt:
    secret: "59f87ecb-8e9a-4942-919a-e32837a95dc1"
    exptime: 1296000000
